/**
 * Export utilities for CodeJournal projects
 */

import { CodeJournalProject, CONTENT_TYPES, ContentType } from './types';

export function exportCodeJournal(project: CodeJournalProject): string {
  return JSON.stringify({
    version: 1,
    exportedAt: Date.now(),
    project: {
      ...project,
      blocks: project.blocks.map(b => {
        const { isEnriching, isError, statusText, ...rest } = b;
        return rest;
      }),
    },
  }, null, 2);
}

export function exportMarkdown(project: CodeJournalProject): string {
  const date = new Date().toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' });
  const enrichedBlocks = project.blocks.filter(b => !b.isError);
  const types = Array.from(new Set(enrichedBlocks.map(b => b.contentType)));

  let md = `---
title: "${project.name}"
date: "${date}"
nodes: ${enrichedBlocks.length}
types: [${types.map(t => `"${t}"`).join(', ')}]
source: CodeJournal
---

# ${project.name}

> **Generated by CodeJournal** · ${date} · ${enrichedBlocks.length} entries

## Overview

| Type | Count |
|------|-------|
`;

  // Type counts
  const counts: Partial<Record<ContentType, number>> = {};
  for (const b of enrichedBlocks) counts[b.contentType] = (counts[b.contentType] || 0) + 1;
  for (const [type, count] of Object.entries(counts)) {
    const cfg = CONTENT_TYPES[type as ContentType];
    md += `| ${cfg.label} | ${count} |\n`;
  }

  md += '\n---\n\n';

  // Group by category
  const byCategory: Record<string, typeof enrichedBlocks> = {};
  for (const b of enrichedBlocks) {
    if (!byCategory[b.category]) byCategory[b.category] = [];
    byCategory[b.category].push(b);
  }

  for (const [category, blocks] of Object.entries(byCategory)) {
    md += `## ${category}\n\n`;
    for (const b of blocks) {
      const cfg = CONTENT_TYPES[b.contentType];
      md += `### [${cfg.label}] ${b.text}\n\n`;
      md += `Confidence: ${b.confidence || '?'}/5\n\n`;
      if (b.annotation) {
        md += `> ${b.annotation}\n\n`;
      }
    }
  }

  return md;
}

export function exportKnowledgeDoc(project: CodeJournalProject): string {
  const date = new Date().toLocaleDateString();
  const blocks = project.blocks.filter(b => !b.isError);

  let md = `# ${project.name} — CodeJournal Export\n\n`;
  md += `*Exported on ${date} · ${blocks.length} entries*\n\n`;

  if (project.synthesis) {
    md += `## Knowledge Summary\n\n${project.synthesis.summary}\n\n`;
    md += `## Blind Spots Identified\n\n`;
    for (const bs of project.synthesis.blindSpots) {
      md += `- ${bs}\n`;
    }
    md += `\n## Today's Assignment\n\n`;
    md += `**${project.synthesis.assignment.title}**\n\n`;
    md += `${project.synthesis.assignment.description}\n\n`;
    md += `*Estimated time: ${project.synthesis.assignment.estimatedMinutes} minutes*\n\n`;
  }

  md += `## Concepts\n\n`;
  const concepts = blocks.filter(b => b.contentType === 'concept' || b.contentType === 'definition');
  for (const c of concepts) {
    md += `### [[${c.text.slice(0, 50)}]]\n\n`;
    if (c.annotation) md += `${c.annotation}\n\n`;
  }

  return md;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
