export const INITIAL_PROJECTS: any[] = [
  {
    id: "p-demo",
    name: "JavaScript Deep Dive",
    blocks: [
      {
        id: "b1",
        text: "Closures capture variables by reference, not by value. When a function is returned from another function, it retains access to the outer scope's variables even after the outer function has finished executing.",
        timestamp: Date.now() - 86400000 * 3,
        contentType: "concept",
        category: "Closures",
        annotation: "This has implications for memory management — closures can inadvertently prevent garbage collection of large objects if they capture references to them. Also worth noting: in a loop with `var`, all closures share the same variable binding, which is why `let` was introduced for block scoping.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "b2",
        text: "Why does setTimeout with 0ms delay still execute after synchronous code? I expected it to run immediately but it always waits.",
        timestamp: Date.now() - 86400000 * 3 + 3600000,
        contentType: "confusion",
        category: "Event Loop",
        annotation: "This is the fundamental distinction between the **call stack** and the **task queue**. Even with 0ms, `setTimeout` callbacks are placed in the macrotask queue and only execute after the current execution context is completely empty. This is why `Promise.then()` (microtask) runs before `setTimeout` (macrotask).",
        isEnriching: false,
        influencedBy: ["b1"],
      },
      {
        id: "b3",
        text: "Edge case: Array.sort() without a comparator converts elements to strings first. So [10, 9, 8].sort() gives [10, 8, 9] because '10' < '8' lexicographically.",
        timestamp: Date.now() - 86400000 * 2,
        contentType: "edgecase",
        category: "Arrays",
        annotation: "This is one of JavaScript's most common gotchas. The default sort is **lexicographic** regardless of element type. For numeric sorting, always pass `(a, b) => a - b`. Also note that `sort()` mutates the original array — use `toSorted()` (ES2023) for an immutable alternative.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "b4",
        text: "I think React re-renders all children of a component even if only one child's props changed. useMemo and React.memo exist to prevent this but I'm not sure when they're actually needed.",
        timestamp: Date.now() - 86400000 * 2 + 7200000,
        contentType: "hypothesis",
        category: "React Rendering",
        annotation: "Partially correct. React re-renders a component when its parent re-renders OR when its own state/context changes. `React.memo` prevents re-render if props are shallowly equal. However, premature memoization adds overhead — the React team recommends profiling first. The new React Compiler (React 19) aims to auto-memoize, making manual `useMemo`/`useCallback` less necessary.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "b5",
        text: "Promises and async/await are not the same thing under the hood. async functions always return a Promise, and await is syntactic sugar for .then(), but error handling differs — try/catch with await vs .catch() chaining.",
        timestamp: Date.now() - 86400000,
        contentType: "concept",
        category: "Async Programming",
        annotation: "Key difference: with `.catch()`, unhandled rejections in the chain can be silently swallowed if you forget to chain properly. With `try/catch` in async/await, the error propagates naturally. However, `await` in a loop is sequential — use `Promise.all()` for concurrent operations. Also note: top-level await is now supported in ES modules.",
        isEnriching: false,
        influencedBy: ["b2"],
      },
      {
        id: "b6",
        text: "The 'this' keyword in JavaScript doesn't refer to the object the function is defined in — it refers to the object that CALLS the function. Arrow functions are different because they inherit 'this' from the enclosing scope.",
        timestamp: Date.now() - 86400000 + 3600000,
        contentType: "concept",
        category: "this Binding",
        annotation: "There are actually 4 rules for `this` binding in order of precedence: **new** binding > explicit binding (call/apply/bind) > implicit binding (method call) > default binding (global/undefined in strict mode). Arrow functions bypass all of these by lexically capturing `this`. This is why arrow functions can't be used as constructors.",
        isEnriching: false,
        influencedBy: ["b1"],
      },
      {
        id: "b7",
        text: "Figured out why my useEffect was running twice in development — React 18 StrictMode intentionally double-invokes effects to help find bugs with missing cleanup functions. It only happens in dev, not production.",
        timestamp: Date.now() - 43200000,
        contentType: "resolved",
        category: "React Hooks",
        annotation: "This is React's way of stress-testing your effects for **idempotency**. If your effect breaks when run twice, it likely has a bug (missing cleanup, duplicate subscriptions, etc.). The fix is always to return a proper cleanup function. This also catches issues with effects that assume they run exactly once.",
        isEnriching: false,
        influencedBy: ["b4"],
      },
      {
        id: "b8",
        text: "TypeScript's 'any' vs 'unknown': both accept any value, but 'unknown' forces you to narrow the type before using it. It's the type-safe counterpart to 'any'.",
        timestamp: Date.now() - 36000000,
        contentType: "definition",
        category: "TypeScript",
        annotation: "Think of `unknown` as the **top type** — everything is assignable to it, but it's assignable to nothing without narrowing. `any` effectively disables type checking entirely. A good rule: use `unknown` for values from external sources (API responses, user input) and narrow with type guards. `never` is the opposite — the **bottom type** that represents impossible values.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "b9",
        text: "But the MDN docs say that const prevents reassignment, while some tutorials say const makes things immutable. These contradict — you can still mutate a const object's properties.",
        timestamp: Date.now() - 28800000,
        contentType: "conflict",
        category: "Variables",
        annotation: "`const` only prevents **rebinding** the variable name — it says nothing about the value's mutability. `const obj = {}; obj.x = 1` is perfectly valid. For true immutability, use `Object.freeze()` (shallow) or libraries like Immer. This distinction between binding immutability and value immutability trips up many developers coming from languages where `const` means deep immutability.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "b10",
        text: "The event loop processes ALL microtasks (Promise callbacks, queueMicrotask) before moving to the next macrotask (setTimeout, setInterval, I/O). This means a recursive microtask can starve the macrotask queue.",
        timestamp: Date.now() - 14400000,
        contentType: "edgecase",
        category: "Event Loop",
        annotation: "This is a critical performance consideration. A `Promise.resolve().then(recurse)` loop will block rendering and I/O indefinitely because the browser never gets to process macrotasks (which include rendering frames). This is why infinite microtask loops freeze the UI completely, while infinite `setTimeout` loops at least allow rendering between iterations.",
        isEnriching: false,
        influencedBy: ["b2", "b5"],
      },
      {
        id: "b11",
        text: "I think the V8 engine optimizes functions that are called with consistent argument types (monomorphic) much better than functions called with varying types (polymorphic). This might explain why TypeScript code can be faster.",
        timestamp: Date.now() - 7200000,
        contentType: "hypothesis",
        category: "Performance",
        annotation: "Correct intuition. V8 uses **inline caches** that specialize based on observed types. Monomorphic call sites get fast machine code paths. After seeing 4+ different shapes, V8 gives up and falls back to a slow **megamorphic** lookup. TypeScript doesn't directly help V8 (types are erased), but the discipline of consistent types that TS encourages does align with what V8 optimizes for.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "b12",
        text: "WeakMap and WeakSet hold 'weak' references to their keys, meaning the keys can be garbage collected if there are no other references to them. Regular Map/Set prevent garbage collection of their entries.",
        timestamp: Date.now() - 3600000,
        contentType: "concept",
        category: "Memory Management",
        annotation: "The primary use case for `WeakMap` is associating metadata with objects without preventing their cleanup — e.g., caching computed values, storing private data, or tracking DOM nodes. Unlike `Map`, `WeakMap` is not iterable and has no `.size` property because its contents are non-deterministic (GC can run at any time). This makes it perfect for caches that shouldn't cause memory leaks.",
        isEnriching: false,
        influencedBy: ["b1"],
      },
    ],
    collapsedIds: [],
    ghostNotes: [],
  },
  {
    id: "p-python",
    name: "Python Patterns",
    blocks: [
      {
        id: "py1",
        text: "Python's GIL (Global Interpreter Lock) means only one thread can execute Python bytecode at a time. This makes CPU-bound multithreading useless — you need multiprocessing instead.",
        timestamp: Date.now() - 86400000 * 2,
        contentType: "concept",
        category: "Concurrency",
        annotation: "The GIL is a CPython implementation detail, not a language requirement. Jython and IronPython don't have it. For I/O-bound tasks, threading still helps because the GIL is released during I/O operations. For CPU-bound work, use `multiprocessing`, `concurrent.futures.ProcessPoolExecutor`, or the new `subinterpreters` module (Python 3.12+).",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "py2",
        text: "List comprehensions create a new list in memory. For large datasets, generator expressions (parentheses instead of brackets) are lazy and memory-efficient.",
        timestamp: Date.now() - 86400000,
        contentType: "concept",
        category: "Iterators",
        annotation: "Generators yield one item at a time and can represent infinite sequences. However, they're **single-use** — once exhausted, they can't be restarted. If you need to iterate multiple times, use `itertools.tee()` or materialize to a list. Also note: dict/set comprehensions exist too (`{k: v for ...}` and `{x for ...}`).",
        isEnriching: false,
        influencedBy: ["py1"],
      },
      {
        id: "py3",
        text: "Default mutable arguments in Python are shared across all calls! def append_to(element, lst=[]): lst.append(element) — this lst is the SAME list every time the function is called.",
        timestamp: Date.now() - 43200000,
        contentType: "edgecase",
        category: "Functions",
        annotation: "This is Python's most infamous gotcha. Default arguments are evaluated **once** at function definition time, not at each call. The fix is `def append_to(element, lst=None): if lst is None: lst = []`. This applies to all mutable defaults: lists, dicts, sets. The same principle explains why you shouldn't use mutable class attributes as instance defaults.",
        isEnriching: false,
        influencedBy: [],
      },
      {
        id: "py4",
        text: "Decorators are just functions that take a function and return a function. @decorator is syntactic sugar for func = decorator(func). They can be stacked and parameterized.",
        timestamp: Date.now() - 21600000,
        contentType: "definition",
        category: "Decorators",
        annotation: "At a deeper level, decorators leverage **closures** to wrap behavior around functions. Parameterized decorators like `@retry(max_attempts=3)` are actually decorator *factories* — functions that return decorators. Always use `@functools.wraps(func)` inside your decorator to preserve the wrapped function's `__name__`, `__doc__`, and other metadata.",
        isEnriching: false,
        influencedBy: ["py2"],
      },
      {
        id: "py5",
        text: "I'm confused about when to use __str__ vs __repr__. Both return strings but they seem to serve different purposes and I keep mixing them up.",
        timestamp: Date.now() - 10800000,
        contentType: "confusion",
        category: "Magic Methods",
        annotation: "`__repr__` is for developers — it should be unambiguous and ideally valid Python that could recreate the object (e.g., `Point(x=3, y=4)`). `__str__` is for end users — it should be readable and pretty. If only one is defined, implement `__repr__` because `str()` falls back to it, but `repr()` never falls back to `__str__`.",
        isEnriching: false,
        influencedBy: [],
      },
    ],
    collapsedIds: [],
    ghostNotes: [],
  },
  {
    id: "p-empty",
    name: "✨ New Session",
    blocks: [],
    collapsedIds: [],
    ghostNotes: [],
  },
]

